remove hardcoded dates, download release schedule from salsa.debian.org, improve error handling (#2)

diff --git a/check_os_release b/check_os_release
--- a/check_os_release
+++ b/check_os_release
@@ -1,58 +1,25 @@
 #!/bin/bash
 
-VERSION="18.01.1"
-
 # check_os_release
 # https://github.com/hobbyquaker/check_os_release
 #
 # Simple Nagios/Icinga check for support end of Linux distributions.
 #
 # Currently only Debian, Raspbian and Ubuntu are supported, Pull Requests welcome!
-# MIT Licensed, Copyright 2018 https://github.com/hobbyquaker
+# MIT Licensed, Copyright 2018, 2019 https://github.com/hobbyquaker
 
-declare -A ubuntu_eol=(
-    ["14.04"]="2019-04-01"
-    ["14.10"]="2015-07-23"
-    ["15.04"]="2016-02-04"
-    ["15.10"]="2016-07-28"
-    ["16.04"]="2021-04-01"
-    ["16.10"]="2017-07-20"
-    ["17.04"]="2018-01-13"
-    ["17.10"]="2018-10-19"
-    ["18.04"]="2023-04-01"
+VERSION="2.0"
 
-    # TBD
-    ["18.10"]="2018-10-01"
-    ["19.04"]="2020-04-01"
-    ["19.10"]="2020-10-01"
-    ["20.04"]="2025-04-01"
-)
-
-declare -A debian_lts=(
-    ["6"]="2016-02-29"
-    ["7"]="2018-05-31"
-    ["8"]="2020-04-30"
-    ["9"]="2022-06-30"
-
-    # TBD
-    ["10"]="2024-04-01"
-    ["11"]="2026-04-01"
-)
-
-declare -A debian_eol=(
-    ["6"]="2016-02-29"
-    ["7"]="2016-04-26"
-    ["8"]="2018-05-31"
-    ["9"]="2020-05-30"
-
-    #TBD
-    ["10"]="2022-04-01"
-    ["11"]="2024-04-01"
-)
+RELEASE_FILE="/etc/os-release"
+DEBIAN_URL="https://salsa.debian.org/debian/distro-info-data/raw/master/debian.csv"
+UBUNTU_URL="https://salsa.debian.org/debian/distro-info-data/raw/master/ubuntu.csv"
+SCHEDULE_FILE="/tmp/os_release_schedule.csv"
+SCHEDULE_FILE_MAXAGE=30
 
 WARN_MONTHS=3
 CRIT_MONTHS=1
 DEB_LTS=0
+
 
 while getopts 'w:c:lhv' OPT; do
   case $OPT in
@@ -76,24 +43,28 @@ while getopts 'w:c:lhv' OPT; do
   esac
 done
 
+
 WARNING=$(date --date="+$WARN_MONTHS month" +"%Y-%m-%d")
 CRITICAL=$(date --date="+$CRIT_MONTHS month" +"%Y-%m-%d")
 TODAY=$(date +"%Y-%m-%d")
 
-source /etc/os-release
+
+if [ ! -f $RELEASE_FILE ]; then
+    echo "UNKNOWN: $RELEASE_FILE missing"
+    exit 3
+fi
+
+source $RELEASE_FILE
 
 case "$ID" in
     "ubuntu")
-        EOL=${ubuntu_eol[$VERSION_ID]}
+        REGEX="^$(echo $VERSION_ID | sed 's/\./\\./g')\s*\(LTS\)\?,"
+        URL=$UBUNTU_URL
         ;;
     "debian") ;&
     "raspbian")
-        if [ $DEB_LTS -eq 0 ]
-        then
-            EOL=${debian_eol[$VERSION_ID]}
-        else
-            EOL=${debian_lts[$VERSION_ID]}
-        fi
+        REGEX="^$(echo $VERSION_ID | sed 's/\./\\./g'),"
+        URL=$DEBIAN_URL
         ;;
     *)
         # TODO other Distributions...
@@ -102,19 +73,62 @@ case "$ID" in
         ;;
 esac
 
-if [ $EOL \< $TODAY ]
-then
-    echo "CRITICAL: Support for $ID $VERSION_ID ended at $EOL"
+
+if [ ! -f $SCHEDULE_FILE ]; then
+    wget -q $URL -O $SCHEDULE_FILE.tmp
+    if [ $? -ne 0 ]; then
+        echo "UNKNOWN: failed to download release schedule from $URL"
+        exit 3
+    else
+        mv $SCHEDULE_FILE.tmp $SCHEDULE_FILE
+    fi
+elif [[ $(find "$SCHEDULE_FILE" -mtime +$SCHEDULE_FILE_MAXAGE -print) ]]; then
+    wget -q $URL -O $SCHEDULE_FILE && mv $SCHEDULE_FILE.tmp $SCHEDULE_FILE
+fi
+
+
+LINE=$(cat $SCHEDULE_FILE | grep $REGEX)
+
+if [ -z "$LINE" ]; then
+    echo "UNKNOWN: $ID $VERSION_ID not found in release schedule"
+    exit 3
+fi
+
+
+VERSION=$(echo $LINE | cut -d ',' -f1)
+CODENAME=$(echo $LINE | cut -d ',' -f2)
+RELEASE=$(echo $LINE | cut -d ',' -f5)
+
+
+if [ $DEB_LTS -ne 0 ] && [ "$ID" = "debian" ]; then
+    EOL=$(date --date="$RELEASE+5 years" +"%Y-%m-%d")
+    ESTIMATE=" (estimated)"
+    SUPPORT="LTS"
+else
+    EOL=$(echo $LINE | cut -d ',' -f6)
+    SUPPORT="Support"
+fi
+
+
+if [ -z "$EOL" ] && [ "$ID_LIKE" = "debian" ]; then
+    EOL=$(date --date="$RELEASE+3 years" +"%Y-%m-%d")
+    ESTIMATE=" (estimated)"
+elif [ -z "$EOL" ]; then
+    echo "UNKNOWN: EOL Date for $ID $VERSION_ID not found in release schedule"
+    exit 3
+fi
+
+
+if [ $EOL \< $TODAY ]; then
+    echo "CRITICAL: ${SUPPORT} for $NAME $VERSION ($CODENAME) ended $EOL$ESTIMATE"
     exit 2
-elif [ $EOL \< $CRITICAL ]
-then
-    echo "CRITICAL: Support for $ID $VERSION_ID ends at $EOL"
+elif [ $EOL \< $CRITICAL ]; then
+    echo "CRITICAL: ${SUPPORT} for $NAME $VERSION ($CODENAME) ends $EOL$ESTIMATE"
     exit 2
-elif [ $EOL \< $WARNING ]
-then
-    echo "WARNING: Support for $ID $VERSION_ID ends at $EOL"
+elif [ $EOL \< $WARNING ]; then
+    echo "WARNING: ${SUPPORT} for $NAME $VERSION ($CODENAME) ends $EOL$ESTIMATE"
     exit 1
 else
-    echo "OK: Support for $ID $VERSION_ID ends at $EOL"
+    echo "OK: ${SUPPORT} for $NAME $VERSION ($CODENAME) ends $EOL$ESTIMATE"
     exit 0
 fi
